config/routes.rb
Rails.application.routes.draw do
  resources :listing_types
  resources :shop_locations
  resources :sub_catogories
  
  resources :product_types
  resources :vendors
  
  resources :variants
  resources :option_value_sets
  resources :option_type_sets
  resources :products do
    resources :option_types 
  end 

  resources :variants 
  resources :vendors, only: [] do
    member do
      get :code
    end
  end
  resources :categories do
    get :sub_categories, on: :member
  end

  
  
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "products#new"
   post 'create_variants', to: 'products#create_variants'
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: %i[ show edit update destroy ]

  # GET /product_types or /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1 or /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types or /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to product_type_url(@product_type), notice: "Product type was successfully created." }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1 or /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to product_type_url(@product_type), notice: "Product type was successfully updated." }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1 or /product_types/1.json
  def destroy
    @product_type.destroy

    respond_to do |format|
      format.html { redirect_to product_types_url, notice: "Product type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_type_params
      params.require(:product_type).permit(:name)
    end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_form.html.erb
<%= simple_form_for(@product_type) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/product_types/_product_type.html.erb
<div id="<%= dom_id product_type %>">
  <p>
    <strong>Name:</strong>
    <%= product_type.name %>
  </p>

</div>

app/views/product_types/edit.html.erb
<h1>Editing product type</h1>

<%= render "form", product_type: @product_type %>

<br>

<div>
  <%= link_to "Show this product type", @product_type %> |
  <%= link_to "Back to product types", product_types_path %>
</div>

app/views/product_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Product types</h1>

<div id="product_types">
  <% @product_types.each do |product_type| %>
    <%= render product_type %>
    <p>
      <%= link_to "Show this product type", product_type %>
    </p>
  <% end %>
</div>

<%= link_to "New product type", new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New product type</h1>

<%= render "form", product_type: @product_type %>

<br>

<div>
  <%= link_to "Back to product types", product_types_path %>
</div>

app/views/product_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product_type %>

<div>
  <%= link_to "Edit this product type", edit_product_type_path(@product_type) %> |
  <%= link_to "Back to product types", product_types_path %>

  <%= button_to "Destroy this product type", @product_type, method: :delete %>
</div>