config/routes.rb
Rails.application.routes.draw do
  resources :listing_types
  resources :shop_locations
  resources :sub_catogories
  
  resources :product_types
  resources :vendors
  
  resources :variants
  resources :option_value_sets
  resources :option_type_sets
  resources :products do
    resources :option_types 
  end 

  resources :variants 
  resources :vendors, only: [] do
    member do
      get :code
    end
  end
  resources :categories do
    get :sub_categories, on: :member
  end

  
  
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "products#new"
   post 'create_variants', to: 'products#create_variants'
end

app/models/option_value_variant.rb
class OptionValueVariant < ApplicationRecord
    belongs_to :option_value
    belongs_to :variant
  
    validates_presence_of :option_value
    validates_presence_of :variant
    validates_uniqueness_of :option_value_id, scope: :variant_id
  end
  

app/controllers/option_value_variants_controller.rb
class OptionValueVariantsController < ApplicationController
  before_action :set_option_value_variant, only: %i[ show edit update destroy ]

  # GET /option_value_variants or /option_value_variants.json
  def index
    @option_value_variants = OptionValueVariant.all
  end

  # GET /option_value_variants/1 or /option_value_variants/1.json
  def show
  end

  # GET /option_value_variants/new
  def new
    @option_value_variant = OptionValueVariant.new
  end

  # GET /option_value_variants/1/edit
  def edit
  end

  # POST /option_value_variants or /option_value_variants.json
  def create
    @option_value_variant = OptionValueVariant.new(option_value_variant_params)

    respond_to do |format|
      if @option_value_variant.save
        format.html { redirect_to option_value_variant_url(@option_value_variant), notice: "Option value variant was successfully created." }
        format.json { render :show, status: :created, location: @option_value_variant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @option_value_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /option_value_variants/1 or /option_value_variants/1.json
  def update
    respond_to do |format|
      if @option_value_variant.update(option_value_variant_params)
        format.html { redirect_to option_value_variant_url(@option_value_variant), notice: "Option value variant was successfully updated." }
        format.json { render :show, status: :ok, location: @option_value_variant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @option_value_variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /option_value_variants/1 or /option_value_variants/1.json
  def destroy
    @option_value_variant.destroy

    respond_to do |format|
      format.html { redirect_to option_value_variants_url, notice: "Option value variant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option_value_variant
      @option_value_variant = OptionValueVariant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def option_value_variant_params
      params.fetch(:option_value_variant, {})
    end
end

app/helpers/option_value_variants_helper.rb
module OptionValueVariantsHelper
end

app/views/option_value_variants/_form.html.erb
<%= simple_form_for(@option_value_variant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/option_value_variants/_option_value_variant.html.erb
<div id="<%= dom_id option_value_variant %>">
</div>

app/views/option_value_variants/edit.html.erb
<h1>Editing option value variant</h1>

<%= render "form", option_value_variant: @option_value_variant %>

<br>

<div>
  <%= link_to "Show this option value variant", @option_value_variant %> |
  <%= link_to "Back to option value variants", option_value_variants_path %>
</div>

app/views/option_value_variants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Option value variants</h1>

<div id="option_value_variants">
  <% @option_value_variants.each do |option_value_variant| %>
    <%= render option_value_variant %>
    <p>
      <%= link_to "Show this option value variant", option_value_variant %>
    </p>
  <% end %>
</div>

<%= link_to "New option value variant", new_option_value_variant_path %>

app/views/option_value_variants/new.html.erb
<h1>New option value variant</h1>

<%= render "form", option_value_variant: @option_value_variant %>

<br>

<div>
  <%= link_to "Back to option value variants", option_value_variants_path %>
</div>

app/views/option_value_variants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @option_value_variant %>

<div>
  <%= link_to "Edit this option value variant", edit_option_value_variant_path(@option_value_variant) %> |
  <%= link_to "Back to option value variants", option_value_variants_path %>

  <%= button_to "Destroy this option value variant", @option_value_variant, method: :delete %>
</div>