config/routes.rb
Rails.application.routes.draw do
  resources :listing_types
  resources :shop_locations
  resources :sub_catogories
  
  resources :product_types
  resources :vendors
  
  resources :variants
  resources :option_value_sets
  resources :option_type_sets
  resources :products do
    resources :option_types 
  end 

  resources :variants 
  resources :vendors, only: [] do
    member do
      get :code
    end
  end
  resources :categories do
    get :sub_categories, on: :member
  end

  
  
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "products#new"
   post 'create_variants', to: 'products#create_variants'
end

app/models/option_value_set.rb
class OptionValueSet < ApplicationRecord
    belongs_to :option_type_set
    
    

end

app/controllers/option_value_sets_controller.rb
class OptionValueSetsController < ApplicationController
  before_action :set_option_value_set, only: %i[ show edit update destroy ]

  # GET /option_value_sets or /option_value_sets.json
  def index
    @option_value_sets = OptionValueSet.all
  end

  # GET /option_value_sets/1 or /option_value_sets/1.json
  def show
  end

  # GET /option_value_sets/new
  def new
    @option_value_set = OptionValueSet.new
  end

  # GET /option_value_sets/1/edit
  def edit
  end

  # POST /option_value_sets or /option_value_sets.json
  def create
    @option_value_set = OptionValueSet.new(option_value_set_params)

    respond_to do |format|
      if @option_value_set.save
        format.html { redirect_to option_value_set_url(@option_value_set), notice: "Option value set was successfully created." }
        format.json { render :show, status: :created, location: @option_value_set }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @option_value_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /option_value_sets/1 or /option_value_sets/1.json
  def update
    respond_to do |format|
      if @option_value_set.update(option_value_set_params)
        format.html { redirect_to option_value_set_url(@option_value_set), notice: "Option value set was successfully updated." }
        format.json { render :show, status: :ok, location: @option_value_set }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @option_value_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /option_value_sets/1 or /option_value_sets/1.json
  def destroy
    @option_value_set.destroy

    respond_to do |format|
      format.html { redirect_to option_value_sets_url, notice: "Option value set was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option_value_set
      @option_value_set = OptionValueSet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def option_value_set_params
      params.fetch(:option_value_set, {})
    end
end

app/helpers/option_value_sets_helper.rb
module OptionValueSetsHelper
end

app/views/option_value_sets/_form.html.erb
<%= simple_form_for(@option_value_set) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/option_value_sets/_option_value_set.html.erb
<div id="<%= dom_id option_value_set %>">
</div>

app/views/option_value_sets/edit.html.erb
<h1>Editing option value set</h1>

<%= render "form", option_value_set: @option_value_set %>

<br>

<div>
  <%= link_to "Show this option value set", @option_value_set %> |
  <%= link_to "Back to option value sets", option_value_sets_path %>
</div>

app/views/option_value_sets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Option value sets</h1>

<div id="option_value_sets">
  <% @option_value_sets.each do |option_value_set| %>
    <%= render option_value_set %>
    <p>
      <%= link_to "Show this option value set", option_value_set %>
    </p>
  <% end %>
</div>

<%= link_to "New option value set", new_option_value_set_path %>

app/views/option_value_sets/new.html.erb
<h1>New option value set</h1>

<%= render "form", option_value_set: @option_value_set %>

<br>

<div>
  <%= link_to "Back to option value sets", option_value_sets_path %>
</div>

app/views/option_value_sets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @option_value_set %>

<div>
  <%= link_to "Edit this option value set", edit_option_value_set_path(@option_value_set) %> |
  <%= link_to "Back to option value sets", option_value_sets_path %>

  <%= button_to "Destroy this option value set", @option_value_set, method: :delete %>
</div>